export const ASSET_NAMES: Record<string, string> = {
  // Stablecoins & Fiat
  USDT: 'Tether USD',
  BUSD: 'Binance USD',
  USDC: 'USD Coin',
  FDUSD: 'First Digital USD',
  DAI: 'Dai Stablecoin',
  EUR: 'Euro',
  GBP: 'British Pound',
  BRL: 'Brazilian Real',
  TRY: 'Turkish Lira',
  RUB: 'Russian Ruble',
  UAH: 'Ukrainian Hryvnia',
  AUD: 'Australian Dollar',
  PLN: 'Polish Zloty',
  ZAR: 'South African Rand',
  ARS: 'Argentine Peso',
  COP: 'Colombian Peso',
  MXN: 'Mexican Peso',
  JPY: 'Japanese Yen',

  // Major Cryptocurrencies
  BTC: 'Bitcoin',
  ETH: 'Ethereum',
  BNB: 'BNB (Binance Coin)',
  SOL: 'Solana',
  XRP: 'Ripple',
  ADA: 'Cardano',
  DOGE: 'Dogecoin',
  SHIB: 'Shiba Inu',
  DOT: 'Polkadot',
  LTC: 'Litecoin',
  TRX: 'TRON',
  MATIC: 'Polygon',
  AVAX: 'Avalanche',
  LINK: 'Chainlink',
  ETC: 'Ethereum Classic',
  UNI: 'Uniswap',
  XLM: 'Stellar Lumens',
  ATOM: 'Cosmos',
  ICP: 'Internet Computer',
  FIL: 'Filecoin',
  LDO: 'Lido DAO',
  APT: 'Aptos',
  HBAR: 'Hedera',
  NEAR: 'NEAR Protocol',
  VET: 'VeChain',
  AAVE: 'Aave',
  GRT: 'The Graph',
  MKR: 'Maker',
  ALGO: 'Algorand',
  THETA: 'Theta Network',
  FANTOM: 'FTM',
  FTM: 'Fantom',
  SAND: 'The Sandbox',
  MANA: 'Decentraland',
  FLOW: 'Flow',
  XTZ: 'Tezos',
  EGLD: 'MultiversX',
  AXS: 'Axie Infinity',
  CHZ: 'Chiliz',
  CRV: 'Curve DAO Token',
  COMP: 'Compound',
  ENJ: 'Enjin Coin',
  GALA: 'Gala Games',
  HOT: 'Holo',
  ONE: 'Harmony',
  RUNE: 'THORChain',
  ZIL: 'Zilliqa',
  BAT: 'Basic Attention Token',
  QTUM: 'Qtum',
  RVN: 'Ravencoin',
  ANKR: 'Ankr',
  GMT: 'STEPN',
  KAVA: 'Kava',
  LRC: 'Loopring',
  MINA: 'Mina Protocol',
  WOO: 'WOO Network',
  ZEC: 'Zcash',
  XMR: 'Monero',
  BCH: 'Bitcoin Cash',
  LUNA: 'Terra',
  LUNC: 'Terra Classic',
  USTC: 'TerraClassicUSD',
  WAVES: 'Waves',
  NEO: 'Neo',
  KSM: 'Kusama',
  CELO: 'Celo',
  NEXO: 'Nexo',
  DASH: 'Dash',
  OMG: 'OMG Network',
  JST: 'JUST',
  SUN: 'SUN',
  IOST: 'IOST',
  ONT: 'Ontology',
  SC: 'Siacoin',
  DGB: 'DigiByte',
  SYS: 'Syscoin',
  CTSI: 'Cartesi',
  AR: 'Arweave',
  KNC: 'Kyber Network',
  CHR: 'Chromia',
  HNT: 'Helium',
  GLMR: 'Moonbeam',
  ZRX: '0x',
  ICX: 'ICON',
  LSK: 'Lisk',
  WAXP: 'WAX',
  VTHO: 'VeThor Token',
  NANO: 'XNO (Nano)',
  XVG: 'Verge',
};
