import type { EndpointConfig } from '../types/binance';

export const KLINE_INTERVALS = [
  '1m','3m','5m','15m','30m',
  '1h','2h','4h','6h','8h','12h',
  '1d','3d','1w','1M',
];

export const ENDPOINTS: EndpointConfig[] = [
  {
    id: 'ping',
    label: 'Ping',
    path: '/api/v3/ping',
    method: 'GET',
    description: 'Test connectivity to the Binance API and measure latency.',
    params: [],
    category: 'General',
  },
  {
    id: 'serverTime',
    label: 'Server Time',
    path: '/api/v3/time',
    method: 'GET',
    description: 'Get current server time as Unix timestamp and human-readable date.',
    params: [],
    category: 'General',
  },
  {
    id: 'exchangeInfo',
    label: 'Exchange Info',
    path: '/api/v3/exchangeInfo',
    method: 'GET',
    description: 'Current exchange trading rules, all active symbols, filters and rate limits.',
    params: [],
    category: 'General',
  },
  {
    id: 'orderBook',
    label: 'Order Book',
    path: '/api/v3/depth',
    method: 'GET',
    description: 'Order book depth (bids & asks) for a specific trading pair.',
    params: [
      {
        name: 'symbol',
        label: 'Symbol',
        type: 'text',
        required: true,
        defaultValue: 'BTCUSDT',
        placeholder: 'e.g. BTCUSDT',
      },
      {
        name: 'limit',
        label: 'Limit',
        type: 'select',
        required: false,
        defaultValue: '20',
        options: ['5', '10', '20', '50', '100', '500', '1000'],
      },
    ],
    category: 'Market Data',
  },
  {
    id: 'recentTrades',
    label: 'Recent Trades',
    path: '/api/v3/trades',
    method: 'GET',
    description: 'Get a list of recent trades for a symbol.',
    params: [
      {
        name: 'symbol',
        label: 'Symbol',
        type: 'text',
        required: true,
        defaultValue: 'BTCUSDT',
        placeholder: 'e.g. ETHUSDT',
      },
      {
        name: 'limit',
        label: 'Limit',
        type: 'number',
        required: false,
        defaultValue: 20,
        placeholder: '1–1000',
      },
    ],
    category: 'Market Data',
  },
  {
    id: 'klines',
    label: 'Klines / Candlestick',
    path: '/api/v3/klines',
    method: 'GET',
    description: 'Candlestick bars for a symbol with OHLCV data. Renders an interactive TradingView chart.',
    params: [
      {
        name: 'symbol',
        label: 'Symbol',
        type: 'text',
        required: true,
        defaultValue: 'BTCUSDT',
        placeholder: 'e.g. BTCUSDT',
      },
      {
        name: 'interval',
        label: 'Interval',
        type: 'select',
        required: true,
        defaultValue: '1h',
        options: KLINE_INTERVALS,
      },
      {
        name: 'limit',
        label: 'Limit',
        type: 'number',
        required: false,
        defaultValue: 100,
        placeholder: '1–1500',
      },
    ],
    category: 'Market Data',
  },
  {
    id: 'tickerPrice',
    label: 'Ticker Price',
    path: '/api/v3/ticker/price',
    method: 'GET',
    description: 'Latest price for a symbol or all symbols (leave empty for all).',
    params: [
      {
        name: 'symbol',
        label: 'Symbol (optional)',
        type: 'text',
        required: false,
        defaultValue: '',
        placeholder: 'Leave empty for all symbols',
      },
    ],
    category: 'Tickers',
  },
  {
    id: 'ticker24hr',
    label: '24hr Stats',
    path: '/api/v3/ticker/24hr',
    method: 'GET',
    description: '24-hour rolling window price statistics for a symbol.',
    params: [
      {
        name: 'symbol',
        label: 'Symbol',
        type: 'text',
        required: true,
        defaultValue: 'BTCUSDT',
        placeholder: 'e.g. BTCUSDT',
      },
    ],
    category: 'Tickers',
  },
  {
    id: 'bookTicker',
    label: 'Book Ticker',
    path: '/api/v3/ticker/bookTicker',
    method: 'GET',
    description: 'Best price/qty on the order book for a symbol.',
    params: [
      {
        name: 'symbol',
        label: 'Symbol',
        type: 'text',
        required: true,
        defaultValue: 'BTCUSDT',
        placeholder: 'e.g. BTCUSDT',
      },
    ],
    category: 'Tickers',
  },
];

export const ENDPOINT_MAP = Object.fromEntries(ENDPOINTS.map((e) => [e.id, e]));
